### ISSUE TITLE
Due diligence of Android and iOS SDKs

### ISSUE THREAD

**Issue by msp-platforme** [ripe-tech/ripe-sdk-android#37]
## Rationale

Android and iOS SDKs  haven't been updated as much as Javascript SDK, so we must catch up on that debt.

## Description

- Review what exists and what is missing

## Estimation

| Discipline | Estimation |
| --- | --- |
| **Software Development ** | 5 days |

**Comment by BeeMargarida** [comment]
@hugo-gomes I have a question: the Android + iOS SDKs should also contain the implementation of the configurator-prc? They currently have a very outdated implementation of the Image.

**Comment by hugo-gomes** [comment]
@BeeMargarida yes! the end goal here is to have these three different RIPE SDK implementations with feature parity!

**Comment by BeeMargarida** [comment]
The Due diligence findings compiled in a document. Both the SDKs are extremely outdated, and perhaps the iOS SDK would be better to be done in Swift, which is something that perhaps can be discussed.
[SDK-due-diligence.md](https://github.com/ripe-tech/ripe-sdk-android/files/7864887/SDK-due-diligence.md)

**Comment by hugo-gomes** [comment]
@BeeMargarida let's create a presentation out of this findings :)

**Comment by BeeMargarida** [comment]
> @BeeMargarida let's create a presentation out of this findings :)

Just confirming if it is really necessary since it would basically be a dump of the tables that are already in the markdown. And in the future, when we are updating the SDKs, the markdown is easier to use to track what is missing

**Comment by BeeMargarida** [comment]
@hugo-gomes Is it necessary to schedule a presentation for the team?

**Comment by hugo-gomes** [comment]
@BeeMargarida how about this thursday? :)

**Comment by BeeMargarida** [comment]
> @BeeMargarida how about this thursday? :)

Sure, it is going to be a 5 minute presentation :sweat_smile:
